#!/usr/bin/env bash
# Local dev sync: build the plugin and copy the compiled dist into opencode's
# global plugins dir (mirrors how the published npm package loads). opencode
# does NOT follow symlinks in the plugins dir, so we COPY. A top-level bridge
# file (herdr-envoy.ts) is the single entry opencode auto-loads; it re-exports
# the plugin from the dist subdir (which opencode does not scan as top-level
# plugin files). This script generates that bridge — idempotent.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
PLUGINS_DIR="${HOME}/.config/opencode/plugins"
DEST="${PLUGINS_DIR}/herdr-envoy-dist"
BRIDGE="${PLUGINS_DIR}/herdr-envoy.ts"

# build — prefer bun, fall back to the project's tsc via npm.
if command -v bunx >/dev/null 2>&1; then
  ( cd "$HERE" && bunx tsc -p tsconfig.json )
else
  ( cd "$HERE" && npm run --silent build )
fi

mkdir -p "$PLUGINS_DIR"
rm -rf "$DEST"
mkdir -p "$DEST"
cp -r "$HERE/dist/." "$DEST/"

# bridge: the one top-level file opencode auto-loads for this plugin.
cat > "$BRIDGE" <<'EOF'
// Auto-generated by herdr-envoy/sync.sh — do not edit.
// Bridges opencode's global plugin auto-loader to the built plugin entry.
export { default } from "./herdr-envoy-dist/index.js"
EOF

echo "synced (built) $HERE/dist -> $DEST"
echo "bridge: $BRIDGE"
